# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84e2ae4b972465697cab8be65d0a7fe9127479aa07ea56cdd3c1041b7da200cc6ba161181edcbf496cb21c58d3f2d931f960d9c745eee3db10e22ba441f75cbe

test:
  secret_key_base: 3c6feb6d737fa862c54d8a07e5e6ef5fa4d096cee07762bd1dd72e84ae049731bc5063d88a4d6fd789d311f19c228aef42d9a1bbba07d918df09afb0b63c8a06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
